import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783111243771 implements MigrationInterface {
    name = 'InitialSchema1783111243771'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."visit_notes_escalation_level_enum" AS ENUM('none', 'low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "visit_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "shift_id" uuid NOT NULL, "care_worker_id" uuid NOT NULL, "service_user_id" uuid NOT NULL, "narrative" text, "mood" character varying, "appetite" character varying, "fluid_intake_ml" integer, "continence" character varying, "pain_level" integer, "sleep_quality" character varying, "mobility_notes" text, "attachment_keys" text, "escalation_level" "public"."visit_notes_escalation_level_enum" NOT NULL DEFAULT 'none', "escalation_status" character varying NOT NULL DEFAULT 'none', "escalated_at" TIMESTAMP WITH TIME ZONE, "escalation_notes" text, CONSTRAINT "PK_9c5441cb0abdf6e876f4e8977af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1243c90620abe505afd140619" ON "visit_notes" ("service_user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_21b85396421babd7f426940593" ON "visit_notes" ("shift_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tenants_country_enum" AS ENUM('UK', 'US')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_subscriptiontier_enum" AS ENUM('starter', 'professional', 'enterprise')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "country" "public"."tenants_country_enum" NOT NULL, "subscriptionTier" "public"."tenants_subscriptiontier_enum" NOT NULL DEFAULT 'starter', "subscriptionStatus" character varying NOT NULL DEFAULT 'trial', "stripe_customer_id" character varying, "settings" jsonb NOT NULL DEFAULT '{}', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "nhs_number_enc" character varying, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "date_of_birth" date NOT NULL, "address" jsonb NOT NULL, "contact_details" jsonb, "funding_source" character varying, "care_level" character varying, "status" character varying NOT NULL DEFAULT 'active', "key_safe_code_enc" character varying, "gp_details" jsonb, "allergies" jsonb, "medical_conditions" jsonb, "mobility_needs" text, "communication_needs" text, "emergency_contacts" jsonb, CONSTRAINT "PK_0733c78cc45274ecc054c43cfcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shifts_shift_type_enum" AS ENUM('personal_care', 'medication', 'social', 'overnight', 'sleep_in', 'waking_night', 'live_in', 'supported_living', 'emergency_cover')`);
        await queryRunner.query(`CREATE TYPE "public"."shifts_status_enum" AS ENUM('unassigned', 'assigned', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show')`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "service_user_id" uuid NOT NULL, "care_worker_id" uuid, "manager_id" uuid, "scheduled_start" TIMESTAMP WITH TIME ZONE NOT NULL, "scheduled_end" TIMESTAMP WITH TIME ZONE NOT NULL, "shift_type" "public"."shifts_shift_type_enum" NOT NULL, "status" "public"."shifts_status_enum" NOT NULL DEFAULT 'unassigned', "is_recurring" boolean NOT NULL DEFAULT false, "recurrence_rule" character varying, "recurrence_group_id" uuid, "location_address" jsonb, "location_lat" numeric(9,6), "location_lon" numeric(9,6), "notes" text, "pay_rate_override" numeric(10,4), "published_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid NOT NULL, CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e282e68d8bc10de4158f0e39b" ON "shifts" ("recurrence_group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffd75b5f45b31a27dfc5a54a76" ON "shifts" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_69f16f44d3c8252a526a7cb505" ON "shifts" ("tenant_id", "service_user_id", "scheduled_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_2538948a14fd54d996f68d7dce" ON "shifts" ("tenant_id", "care_worker_id", "scheduled_start") `);
        await queryRunner.query(`CREATE TABLE "payroll_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "period_id" uuid NOT NULL, "care_worker_id" uuid NOT NULL, "hours_regular" numeric(8,2) NOT NULL DEFAULT '0', "hours_overtime" numeric(8,2) NOT NULL DEFAULT '0', "hours_bank_holiday" numeric(8,2) NOT NULL DEFAULT '0', "hours_sleep_in" numeric(8,2) NOT NULL DEFAULT '0', "gross_pay" numeric(12,2) NOT NULL, "paye_tax" numeric(12,2), "employee_ni" numeric(12,2), "employer_ni" numeric(12,2), "employee_pension" numeric(12,2), "employer_pension" numeric(12,2), "ssp_amount" numeric(12,2), "smp_amount" numeric(12,2), "student_loan" numeric(12,2), "federal_income_tax" numeric(12,2), "state_income_tax" numeric(12,2), "social_security_ee" numeric(12,2), "social_security_er" numeric(12,2), "medicare_ee" numeric(12,2), "medicare_er" numeric(12,2), "futa" numeric(12,2), "expenses_reimbursed" numeric(12,2) NOT NULL DEFAULT '0', "other_additions" jsonb NOT NULL DEFAULT '[]', "other_deductions" jsonb NOT NULL DEFAULT '[]', "net_pay" numeric(12,2) NOT NULL, "payslip_s3_key" character varying, "payslip_sent_at" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'draft', CONSTRAINT "PK_869cabe268deb5726e742f2d3f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_de3725c2eb603146ff962bbd88" ON "payroll_records" ("period_id", "care_worker_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payroll_periods_country_enum" AS ENUM('UK', 'US')`);
        await queryRunner.query(`CREATE TYPE "public"."payroll_periods_status_enum" AS ENUM('draft', 'processing', 'approved', 'paid', 'locked')`);
        await queryRunner.query(`CREATE TABLE "payroll_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "period_start" date NOT NULL, "period_end" date NOT NULL, "pay_date" date NOT NULL, "country" "public"."payroll_periods_country_enum" NOT NULL, "status" "public"."payroll_periods_status_enum" NOT NULL DEFAULT 'draft', "processed_at" TIMESTAMP WITH TIME ZONE, "total_gross" numeric(14,2), "total_net" numeric(14,2), "worker_count" integer, CONSTRAINT "PK_2afd9a853dd55d80ef644b74358" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d16564726c5c176c33ada7128c" ON "payroll_periods" ("tenant_id", "period_start", "period_end") `);
        await queryRunner.query(`CREATE TYPE "public"."medications_route_enum" AS ENUM('oral', 'topical', 'inhaled', 'subcutaneous', 'intravenous', 'rectal', 'transdermal', 'nasal', 'ocular', 'otic')`);
        await queryRunner.query(`CREATE TABLE "medications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "service_user_id" uuid NOT NULL, "name" character varying NOT NULL, "generic_name" character varying, "dosage" character varying NOT NULL, "frequency" character varying NOT NULL, "times_of_day" text, "route" "public"."medications_route_enum" NOT NULL, "prescriber" character varying, "prescriber_contact" character varying, "start_date" date, "end_date" date, "barcode" character varying, "stock_level" integer, "storage_instructions" text, "is_controlled" boolean NOT NULL DEFAULT false, "cd_schedule" character varying, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_cdee49fe7cd79db13340150d356" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mar_records_status_enum" AS ENUM('given', 'refused', 'not_available', 'self_administered', 'administered_by_gp', 'waste')`);
        await queryRunner.query(`CREATE TABLE "mar_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "medication_id" uuid NOT NULL, "service_user_id" uuid NOT NULL, "care_worker_id" uuid NOT NULL, "shift_id" uuid, "scheduled_at" TIMESTAMP WITH TIME ZONE NOT NULL, "administered_at" TIMESTAMP WITH TIME ZONE, "status" "public"."mar_records_status_enum" NOT NULL, "dose_given" character varying, "reason_not_given" character varying, "side_effects" character varying, "signature_svg_enc" text, "witness_id" uuid, "witness_sig_enc" text, "barcode_verified" boolean NOT NULL DEFAULT false, "notes" text, CONSTRAINT "PK_915742b01eaf7472adb47834b49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d357b9d415fb2418cece5dac59" ON "mar_records" ("service_user_id", "scheduled_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_44aed9d4d7ce287b6ba6780d46" ON "mar_records" ("medication_id", "scheduled_at") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_tier_enum" AS ENUM('starter', 'professional', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('trialing', 'active', 'past_due', 'cancelled', 'unpaid')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "stripe_customer_id" character varying, "stripe_subscription_id" character varying, "stripe_price_id" character varying, "tier" "public"."subscriptions_tier_enum" NOT NULL DEFAULT 'starter', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'trialing', "current_period_start" TIMESTAMP WITH TIME ZONE, "current_period_end" TIMESTAMP WITH TIME ZONE, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "trial_end" TIMESTAMP WITH TIME ZONE, "seats_used" integer NOT NULL DEFAULT '0', "seats_limit" integer NOT NULL DEFAULT '10', CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f6ac03431c311ccb8bbd7d3af1" ON "subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "invoice_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "invoice_id" uuid NOT NULL, "description" character varying NOT NULL, "shift_id" uuid, "shift_date" date, "quantity" numeric(8,2) NOT NULL, "unit_price" numeric(10,2) NOT NULL, "total" numeric(14,2) NOT NULL, CONSTRAINT "PK_4e8ccaadaf5d0619db9d219b061" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'sent', 'paid', 'overdue', 'void')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "invoice_number" character varying NOT NULL, "service_user_id" uuid NOT NULL, "service_user_name" character varying NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "subtotal" numeric(14,2) NOT NULL DEFAULT '0', "tax_amount" numeric(14,2) NOT NULL DEFAULT '0', "total" numeric(14,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'GBP', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "due_date" date NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE, "sent_at" TIMESTAMP WITH TIME ZONE, "stripe_invoice_id" character varying, "notes" text, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_79c1434cd60d8582bf16858625" ON "invoices" ("service_user_id", "tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7c70191c624dc41d7cbafdc10" ON "invoices" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_701ba9039b36234c51b66a23b5" ON "invoices" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."clock_events_event_type_enum" AS ENUM('clock_in', 'clock_out', 'break_start', 'break_end')`);
        await queryRunner.query(`CREATE TABLE "clock_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "shift_id" uuid NOT NULL, "care_worker_id" uuid NOT NULL, "event_type" "public"."clock_events_event_type_enum" NOT NULL, "recorded_at" TIMESTAMP WITH TIME ZONE NOT NULL, "latitude" numeric(9,6), "longitude" numeric(9,6), "gps_accuracy" numeric(6,2), "gps_distance_m" numeric(8,2), "device_id" character varying, "app_version" character varying, "ip_address" character varying, "is_manual" boolean NOT NULL DEFAULT false, "manual_reason" character varying, "manual_by" uuid, "fraud_flag" boolean NOT NULL DEFAULT false, "fraud_reasons" text, CONSTRAINT "PK_08ee1d588f22ec11fc7771c6a87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a9ef78e517f50b4433d117c8c" ON "clock_events" ("care_worker_id", "recorded_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_38f49202ceceb6f03e762b1a4f" ON "clock_events" ("shift_id", "event_type") `);
        await queryRunner.query(`CREATE TYPE "public"."care_workers_employment_type_enum" AS ENUM('full_time', 'part_time', 'zero_hours', 'contractor', 'bank')`);
        await queryRunner.query(`CREATE TABLE "care_workers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "user_id" uuid NOT NULL, "employee_id" character varying, "employment_type" "public"."care_workers_employment_type_enum" NOT NULL, "contract_start" date, "contract_end" date, "hourly_rate" numeric(10,4) NOT NULL, "weekend_rate" numeric(10,4), "bank_holiday_rate" numeric(10,4), "sleep_in_rate" numeric(10,4), "live_in_daily_rate" numeric(10,4), "pay_frequency" character varying NOT NULL DEFAULT 'weekly', "ni_number_enc" character varying, "tax_code" character varying, "ni_category" character varying NOT NULL DEFAULT 'A', "pension_opt_in" boolean NOT NULL DEFAULT true, "student_loan_plan" character varying, "ssn_enc" character varying, "federal_filing_status" character varying, "bank_account_enc" jsonb, "dbs_cert_number" character varying, "dbs_issued_at" date, "dbs_expires_at" date, "dbs_type" character varying, "rtw_expires_at" date, "vehicle_reg" character varying, "vehicle_insured" boolean NOT NULL DEFAULT false, "emergency_contact" jsonb, "skills" text, "ytd_gross" numeric(12,2) NOT NULL DEFAULT '0', "ytd_tax" numeric(12,2) NOT NULL DEFAULT '0', "ytd_ni" numeric(12,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_6e10d7d0b90b5f677bfd35195e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7470d062b44d6f557b4c19c2a6" ON "care_workers" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "care_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "service_user_id" uuid NOT NULL, "version" integer NOT NULL DEFAULT '1', "title" character varying NOT NULL, "content" jsonb NOT NULL, "risk_assessments" jsonb, "goals" jsonb, "created_by" uuid NOT NULL, "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by" uuid, "next_review_at" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'draft', CONSTRAINT "PK_a8556688bcada6c2729b8c4ac5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_93205f36f2aa3b2eccfd14146c" ON "care_plans" ("service_user_id", "version") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'agency_owner', 'manager', 'care_worker', 'service_user', 'family')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "email" character varying NOT NULL, "password_hash" character varying, "role" "public"."users_role_enum" NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "phone" character varying, "avatar_s3_key" character varying, "is_2fa_enabled" boolean NOT NULL DEFAULT false, "totp_secret_enc" character varying, "biometric_public_key" text, "biometric_device_id" character varying, "last_login_at" TIMESTAMP WITH TIME ZONE, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "google_id" character varying, "apple_id" character varying, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "FK_e554609a06b180dac66a9a977c5" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "FK_e554609a06b180dac66a9a977c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93205f36f2aa3b2eccfd14146c"`);
        await queryRunner.query(`DROP TABLE "care_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7470d062b44d6f557b4c19c2a6"`);
        await queryRunner.query(`DROP TABLE "care_workers"`);
        await queryRunner.query(`DROP TYPE "public"."care_workers_employment_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38f49202ceceb6f03e762b1a4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a9ef78e517f50b4433d117c8c"`);
        await queryRunner.query(`DROP TABLE "clock_events"`);
        await queryRunner.query(`DROP TYPE "public"."clock_events_event_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_701ba9039b36234c51b66a23b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7c70191c624dc41d7cbafdc10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79c1434cd60d8582bf16858625"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_line_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6ac03431c311ccb8bbd7d3af1"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_tier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44aed9d4d7ce287b6ba6780d46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d357b9d415fb2418cece5dac59"`);
        await queryRunner.query(`DROP TABLE "mar_records"`);
        await queryRunner.query(`DROP TYPE "public"."mar_records_status_enum"`);
        await queryRunner.query(`DROP TABLE "medications"`);
        await queryRunner.query(`DROP TYPE "public"."medications_route_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d16564726c5c176c33ada7128c"`);
        await queryRunner.query(`DROP TABLE "payroll_periods"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_periods_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_periods_country_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de3725c2eb603146ff962bbd88"`);
        await queryRunner.query(`DROP TABLE "payroll_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2538948a14fd54d996f68d7dce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69f16f44d3c8252a526a7cb505"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffd75b5f45b31a27dfc5a54a76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e282e68d8bc10de4158f0e39b"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TYPE "public"."shifts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shifts_shift_type_enum"`);
        await queryRunner.query(`DROP TABLE "service_users"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_subscriptiontier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_country_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21b85396421babd7f426940593"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1243c90620abe505afd140619"`);
        await queryRunner.query(`DROP TABLE "visit_notes"`);
        await queryRunner.query(`DROP TYPE "public"."visit_notes_escalation_level_enum"`);
    }

}
