/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/clock-in` | `/clock-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/mar` | `/mar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/visit-notes` | `/visit-notes`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/clock-in` | `/clock-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/mar` | `/mar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/visit-notes` | `/visit-notes`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/clock-in${`?${string}` | `#${string}` | ''}` | `/clock-in${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/mar${`?${string}` | `#${string}` | ''}` | `/mar${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/visit-notes${`?${string}` | `#${string}` | ''}` | `/visit-notes${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/clock-in` | `/clock-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/mar` | `/mar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/visit-notes` | `/visit-notes`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; };
    }
  }
}
