import { Injectable, Logger } from '@nestjs/common';
import { DataSource } from 'typeorm';
import * as ExcelJS from 'exceljs';

const COL_PRIMARY = 'FF1E3A5F';
const COL_HEADER_BG = 'FFE8EFF8';
const COL_ALT_ROW = 'FFF8FAFC';
const COL_BORDER = 'FFCBD5E1';

// ─── Shared Excel helpers ────────────────────────────────────────────────────

function titleRow(ws: ExcelJS.Worksheet, title: string, cols: number) {
  ws.mergeCells(1, 1, 1, cols);
  const cell = ws.getCell('A1');
  cell.value = title;
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COL_PRIMARY } };
  cell.font = { bold: true, size: 13, color: { argb: 'FFFFFFFF' } };
  cell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 };
  ws.getRow(1).height = 26;
}

function subtitleRow(ws: ExcelJS.Worksheet, text: string, cols: number) {
  ws.mergeCells(2, 1, 2, cols);
  const cell = ws.getCell('A2');
  cell.value = text;
  cell.font = { italic: true, color: { argb: 'FF64748B' } };
  cell.alignment = { indent: 1 };
  ws.getRow(2).height = 18;
}

function headerRow(ws: ExcelJS.Worksheet, headers: string[], rowNum = 4) {
  const row = ws.getRow(rowNum);
  headers.forEach((h, i) => {
    const cell = row.getCell(i + 1);
    cell.value = h;
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COL_HEADER_BG } };
    cell.font = { bold: true, color: { argb: COL_PRIMARY }, size: 10 };
    cell.border = { bottom: { style: 'thin', color: { argb: COL_BORDER } } };
    cell.alignment = { vertical: 'middle' };
  });
  row.height = 22;
}

function dataRow(
  ws: ExcelJS.Worksheet,
  values: (string | number | null | undefined)[],
  rowNum: number,
) {
  const row = ws.getRow(rowNum);
  const isAlt = rowNum % 2 === 0;
  values.forEach((v, i) => {
    const cell = row.getCell(i + 1);
    cell.value = v ?? '';
    if (isAlt) {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COL_ALT_ROW } };
    }
    cell.font = { size: 10 };
  });
  row.height = 18;
}

function autoWidth(ws: ExcelJS.Worksheet, cols: number) {
  for (let i = 1; i <= cols; i++) {
    let max = 10;
    ws.getColumn(i).eachCell((cell) => {
      const len = String(cell.value ?? '').length;
      if (len > max) max = len;
    });
    ws.getColumn(i).width = Math.min(max + 4, 50);
  }
}

function footerRow(ws: ExcelJS.Worksheet, rowNum: number, cols: number) {
  ws.mergeCells(rowNum, 1, rowNum, cols);
  const cell = ws.getCell(rowNum, 1);
  cell.value = `Generated by My-Cura on ${new Date().toLocaleString('en-GB')}`;
  cell.font = { italic: true, size: 9, color: { argb: 'FF94A3B8' } };
}

async function toBuffer(wb: ExcelJS.Workbook): Promise<Buffer> {
  return Buffer.from(await wb.xlsx.writeBuffer());
}

// ─── CSV helper ──────────────────────────────────────────────────────────────

function toCsv(headers: string[], rows: (string | number | null | undefined)[][]): string {
  const escape = (v: string | number | null | undefined) => {
    const s = String(v ?? '');
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"`
      : s;
  };
  return [headers, ...rows].map((r) => r.map(escape).join(',')).join('\n');
}

// ─── Service ─────────────────────────────────────────────────────────────────

@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(private readonly dataSource: DataSource) {}

  // ─── 1. Payroll report ────────────────────────────────────────────────────

  async payrollReport(
    tenantId: string,
    from: string,
    to: string,
    format: 'xlsx' | 'csv' = 'xlsx',
  ): Promise<Buffer | string> {
    const rows: Array<{
      worker_name: string;
      employee_number: string;
      period_start: string;
      period_end: string;
      country: string;
      hours_worked: number;
      gross_pay: number;
      income_tax: number;
      ni_employee: number;
      pension_employee: number;
      net_pay: number;
    }> = await this.dataSource.manager.query(
      `SELECT
         CONCAT(u.first_name, ' ', u.last_name) AS worker_name,
         COALESCE(cw.employee_number, '-')       AS employee_number,
         pp.period_start, pp.period_end, pp.country,
         COALESCE(pr.hours_worked, 0)            AS hours_worked,
         COALESCE(pr.gross_pay, 0)               AS gross_pay,
         COALESCE(pr.income_tax, 0)              AS income_tax,
         COALESCE(pr.ni_employee, 0)             AS ni_employee,
         COALESCE(pr.pension_employee, 0)        AS pension_employee,
         COALESCE(pr.net_pay, 0)                 AS net_pay
       FROM payroll_records pr
       JOIN payroll_periods pp ON pp.id = pr.payroll_period_id AND pp.tenant_id = $1
       LEFT JOIN care_workers cw ON cw.id = pr.care_worker_id
       LEFT JOIN users u ON u.id = cw.user_id
       WHERE pp.period_start >= $2 AND pp.period_end <= $3
         AND pr.deleted_at IS NULL AND pp.deleted_at IS NULL
       ORDER BY pp.period_start, worker_name`,
      [tenantId, from, to],
    );

    const HEADERS = [
      'Worker', 'Employee #', 'Period Start', 'Period End', 'Country',
      'Hours', 'Gross Pay', 'Income Tax', 'NI (Employee)', 'Pension', 'Net Pay',
    ];

    if (format === 'csv') {
      return toCsv(
        HEADERS,
        rows.map((r) => [
          r.worker_name, r.employee_number, r.period_start, r.period_end, r.country,
          r.hours_worked, r.gross_pay, r.income_tax, r.ni_employee, r.pension_employee, r.net_pay,
        ]),
      );
    }

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Payroll Report');
    titleRow(ws, 'Payroll Report', HEADERS.length);
    subtitleRow(ws, `Period: ${from} to ${to}`, HEADERS.length);
    headerRow(ws, HEADERS);

    rows.forEach((r, i) => {
      dataRow(ws, [
        r.worker_name, r.employee_number, r.period_start, r.period_end, r.country,
        Number(r.hours_worked), Number(r.gross_pay), Number(r.income_tax),
        Number(r.ni_employee), Number(r.pension_employee), Number(r.net_pay),
      ], i + 5);
    });

    // Totals row
    if (rows.length) {
      const totRow = ws.getRow(rows.length + 5);
      const sum = (key: keyof (typeof rows)[0]) =>
        rows.reduce((acc, r) => acc + Number(r[key]), 0);
      const vals = ['', '', '', '', 'TOTAL', sum('hours_worked'), sum('gross_pay'),
        sum('income_tax'), sum('ni_employee'), sum('pension_employee'), sum('net_pay')];
      vals.forEach((v, i) => {
        const c = totRow.getCell(i + 1);
        c.value = v;
        c.font = { bold: true, color: { argb: COL_PRIMARY } };
        c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COL_HEADER_BG } };
      });
    }

    // Currency format on money columns
    [7, 8, 9, 10, 11].forEach((col) => {
      ws.getColumn(col).numFmt = '£#,##0.00';
    });
    ws.getColumn(6).numFmt = '0.00';

    autoWidth(ws, HEADERS.length);
    footerRow(ws, rows.length + 7, HEADERS.length);
    return toBuffer(wb);
  }

  // ─── 2. Timesheet / attendance report ────────────────────────────────────

  async timesheetReport(
    tenantId: string,
    from: string,
    to: string,
    workerId?: string,
    format: 'xlsx' | 'csv' = 'xlsx',
  ): Promise<Buffer | string> {
    const params: (string | undefined)[] = [tenantId, from, to];
    let workerClause = '';
    if (workerId) { params.push(workerId); workerClause = `AND s.care_worker_id = $${params.length}`; }

    const rows: Array<{
      worker_name: string;
      shift_date: string;
      shift_type: string;
      scheduled_start: string;
      scheduled_end: string;
      actual_start: string | null;
      actual_end: string | null;
      hours_scheduled: number;
      hours_actual: number;
      status: string;
      service_user_name: string;
    }> = await this.dataSource.manager.query(
      `SELECT
         CONCAT(u.first_name, ' ', u.last_name)      AS worker_name,
         s.scheduled_start::date::text               AS shift_date,
         s.shift_type,
         to_char(s.scheduled_start, 'HH24:MI')      AS scheduled_start,
         to_char(s.scheduled_end,   'HH24:MI')      AS scheduled_end,
         to_char(ci.timestamp, 'HH24:MI')           AS actual_start,
         to_char(co.timestamp, 'HH24:MI')           AS actual_end,
         ROUND(EXTRACT(EPOCH FROM (s.scheduled_end - s.scheduled_start))/3600, 2) AS hours_scheduled,
         COALESCE(
           ROUND(EXTRACT(EPOCH FROM (co.timestamp - ci.timestamp))/3600, 2),
           0
         ) AS hours_actual,
         s.status,
         CONCAT(su.first_name, ' ', su.last_name)  AS service_user_name
       FROM shifts s
       LEFT JOIN users u ON u.id = s.care_worker_id
       LEFT JOIN service_users su ON su.id = s.service_user_id AND su.tenant_id = $1
       LEFT JOIN clock_events ci ON ci.shift_id = s.id AND ci.event_type = 'clock_in'
       LEFT JOIN clock_events co ON co.shift_id = s.id AND co.event_type = 'clock_out'
       WHERE s.tenant_id = $1
         AND s.scheduled_start::date BETWEEN $2 AND $3
         ${workerClause}
         AND s.deleted_at IS NULL
       ORDER BY s.scheduled_start, worker_name`,
      params,
    );

    const HEADERS = [
      'Worker', 'Date', 'Shift Type', 'Sched. Start', 'Sched. End',
      'Actual Start', 'Actual End', 'Hrs Scheduled', 'Hrs Actual',
      'Status', 'Service User',
    ];

    if (format === 'csv') {
      return toCsv(HEADERS, rows.map((r) => [
        r.worker_name, r.shift_date, r.shift_type, r.scheduled_start, r.scheduled_end,
        r.actual_start ?? '', r.actual_end ?? '', r.hours_scheduled, r.hours_actual,
        r.status, r.service_user_name,
      ]));
    }

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Timesheet');
    titleRow(ws, 'Timesheet & Attendance Report', HEADERS.length);
    subtitleRow(ws, `${from} to ${to}${workerId ? ' — filtered by worker' : ''}`, HEADERS.length);
    headerRow(ws, HEADERS);

    rows.forEach((r, i) => {
      dataRow(ws, [
        r.worker_name, r.shift_date, r.shift_type.replace(/_/g, ' '),
        r.scheduled_start, r.scheduled_end, r.actual_start ?? '—', r.actual_end ?? '—',
        Number(r.hours_scheduled), Number(r.hours_actual), r.status, r.service_user_name,
      ], i + 5);
    });

    ws.getColumn(8).numFmt = '0.00';
    ws.getColumn(9).numFmt = '0.00';
    autoWidth(ws, HEADERS.length);
    footerRow(ws, rows.length + 6, HEADERS.length);
    return toBuffer(wb);
  }

  // ─── 3. MAR compliance report ─────────────────────────────────────────────

  async marComplianceReport(
    tenantId: string,
    from: string,
    to: string,
    serviceUserId?: string,
    format: 'xlsx' | 'csv' = 'xlsx',
  ): Promise<Buffer | string> {
    const params: (string | undefined)[] = [tenantId, from, to];
    let suClause = '';
    if (serviceUserId) { params.push(serviceUserId); suClause = `AND m.service_user_id = $${params.length}`; }

    const rows: Array<{
      service_user_name: string;
      medication_name: string;
      dosage: string;
      total_scheduled: number;
      given: number;
      refused: number;
      omitted: number;
      compliance_pct: number;
    }> = await this.dataSource.manager.query(
      `SELECT
         CONCAT(su.first_name, ' ', su.last_name) AS service_user_name,
         m.name                                   AS medication_name,
         m.dosage,
         COUNT(mr.id)                             AS total_scheduled,
         COUNT(mr.id) FILTER (WHERE mr.status = 'given')   AS given,
         COUNT(mr.id) FILTER (WHERE mr.status = 'refused') AS refused,
         COUNT(mr.id) FILTER (WHERE mr.status NOT IN ('given','refused')) AS omitted,
         ROUND(
           100.0 * COUNT(mr.id) FILTER (WHERE mr.status = 'given') /
           NULLIF(COUNT(mr.id), 0), 1
         ) AS compliance_pct
       FROM mar_records mr
       JOIN medications m ON m.id = mr.medication_id AND m.tenant_id = $1
       JOIN service_users su ON su.id = m.service_user_id AND su.tenant_id = $1
       WHERE mr.tenant_id = $1
         AND mr.scheduled_time BETWEEN $2 AND $3
         ${suClause}
         AND mr.deleted_at IS NULL
       GROUP BY service_user_name, medication_name, m.dosage
       ORDER BY service_user_name, medication_name`,
      params,
    );

    const HEADERS = [
      'Service User', 'Medication', 'Dosage',
      'Total Scheduled', 'Given', 'Refused', 'Omitted', 'Compliance %',
    ];

    if (format === 'csv') {
      return toCsv(HEADERS, rows.map((r) => [
        r.service_user_name, r.medication_name, r.dosage,
        r.total_scheduled, r.given, r.refused, r.omitted, r.compliance_pct,
      ]));
    }

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('MAR Compliance');
    titleRow(ws, 'MAR Compliance Report', HEADERS.length);
    subtitleRow(ws, `${from} to ${to}`, HEADERS.length);
    headerRow(ws, HEADERS);

    rows.forEach((r, i) => {
      const rowNum = i + 5;
      dataRow(ws, [
        r.service_user_name, r.medication_name, r.dosage,
        Number(r.total_scheduled), Number(r.given), Number(r.refused),
        Number(r.omitted), Number(r.compliance_pct),
      ], rowNum);

      // Color compliance cell
      const pct = Number(r.compliance_pct);
      const compCell = ws.getRow(rowNum).getCell(8);
      compCell.fill = {
        type: 'pattern', pattern: 'solid',
        fgColor: { argb: pct >= 95 ? 'FFD1FAE5' : pct >= 80 ? 'FFFEF3C7' : 'FFFEE2E2' },
      };
      compCell.font = { bold: true, color: { argb: pct >= 95 ? 'FF065F46' : pct >= 80 ? 'FF92400E' : 'FF991B1B' } };
    });

    ws.getColumn(8).numFmt = '0.0"%"';
    autoWidth(ws, HEADERS.length);
    footerRow(ws, rows.length + 6, HEADERS.length);
    return toBuffer(wb);
  }

  // ─── 4. Incident report ───────────────────────────────────────────────────

  async incidentReport(
    tenantId: string,
    from: string,
    to: string,
    severity?: string,
    format: 'xlsx' | 'csv' = 'xlsx',
  ): Promise<Buffer | string> {
    const params: (string | undefined)[] = [tenantId, from, to];
    let sevClause = '';
    if (severity) { params.push(severity); sevClause = `AND i.severity = $${params.length}`; }

    const rows: Array<{
      reported_at: string;
      incident_type: string;
      severity: string;
      service_user_name: string;
      reported_by_name: string;
      description: string;
      actions_taken: string | null;
      resolved_at: string | null;
      cqc_reportable: boolean;
    }> = await this.dataSource.manager.query(
      `SELECT
         to_char(i.reported_at, 'YYYY-MM-DD HH24:MI') AS reported_at,
         i.incident_type,
         i.severity,
         CONCAT(su.first_name, ' ', su.last_name)     AS service_user_name,
         CONCAT(u.first_name, ' ', u.last_name)       AS reported_by_name,
         i.description,
         i.actions_taken,
         to_char(i.resolved_at, 'YYYY-MM-DD')         AS resolved_at,
         COALESCE(i.cqc_reportable, false)            AS cqc_reportable
       FROM incidents i
       LEFT JOIN service_users su ON su.id = i.service_user_id AND su.tenant_id = $1
       LEFT JOIN users u ON u.id = i.reported_by
       WHERE i.tenant_id = $1
         AND i.reported_at BETWEEN $2 AND $3
         ${sevClause}
         AND i.deleted_at IS NULL
       ORDER BY i.reported_at DESC`,
      params,
    );

    const HEADERS = [
      'Date & Time', 'Type', 'Severity', 'Service User',
      'Reported By', 'Description', 'Actions Taken', 'Resolved', 'CQC Reportable',
    ];

    if (format === 'csv') {
      return toCsv(HEADERS, rows.map((r) => [
        r.reported_at, r.incident_type, r.severity, r.service_user_name,
        r.reported_by_name, r.description, r.actions_taken ?? '', r.resolved_at ?? 'Open',
        r.cqc_reportable ? 'Yes' : 'No',
      ]));
    }

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Incidents');
    titleRow(ws, 'Incident Report', HEADERS.length);
    subtitleRow(ws, `${from} to ${to}${severity ? ` — ${severity} severity` : ''}`, HEADERS.length);
    headerRow(ws, HEADERS);

    rows.forEach((r, i) => {
      const rowNum = i + 5;
      dataRow(ws, [
        r.reported_at, r.incident_type.replace(/_/g, ' '), r.severity,
        r.service_user_name, r.reported_by_name, r.description,
        r.actions_taken ?? '—', r.resolved_at ?? 'Open',
        r.cqc_reportable ? 'Yes' : 'No',
      ], rowNum);

      const sevCell = ws.getRow(rowNum).getCell(3);
      const sev = r.severity;
      sevCell.fill = {
        type: 'pattern', pattern: 'solid',
        fgColor: { argb: sev === 'critical' ? 'FFFEE2E2' : sev === 'high' ? 'FFFEF3C7' : 'FFF0FDF4' },
      };
      sevCell.font = { bold: true, color: { argb: sev === 'critical' ? 'FF991B1B' : sev === 'high' ? 'FF92400E' : 'FF166534' } };
    });

    ws.getColumn(6).width = 50;
    ws.getColumn(7).width = 40;
    autoWidth(ws, HEADERS.length);
    footerRow(ws, rows.length + 6, HEADERS.length);
    return toBuffer(wb);
  }

  // ─── 5. Care hours report ─────────────────────────────────────────────────

  async careHoursReport(
    tenantId: string,
    from: string,
    to: string,
    format: 'xlsx' | 'csv' = 'xlsx',
  ): Promise<Buffer | string> {
    const rows: Array<{
      service_user_name: string;
      shift_type: string;
      total_shifts: number;
      completed_shifts: number;
      total_hours: number;
    }> = await this.dataSource.manager.query(
      `SELECT
         CONCAT(su.first_name, ' ', su.last_name) AS service_user_name,
         s.shift_type,
         COUNT(*)                                 AS total_shifts,
         COUNT(*) FILTER (WHERE s.status = 'completed') AS completed_shifts,
         ROUND(SUM(
           EXTRACT(EPOCH FROM (s.scheduled_end - s.scheduled_start)) / 3600
         ), 2)                                    AS total_hours
       FROM shifts s
       JOIN service_users su ON su.id = s.service_user_id AND su.tenant_id = $1
       WHERE s.tenant_id = $1
         AND s.scheduled_start::date BETWEEN $2 AND $3
         AND s.deleted_at IS NULL
       GROUP BY service_user_name, s.shift_type
       ORDER BY service_user_name, s.shift_type`,
      [tenantId, from, to],
    );

    const HEADERS = [
      'Service User', 'Shift Type', 'Total Shifts', 'Completed', 'Hours',
    ];

    if (format === 'csv') {
      return toCsv(HEADERS, rows.map((r) => [
        r.service_user_name, r.shift_type, r.total_shifts, r.completed_shifts, r.total_hours,
      ]));
    }

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Care Hours');
    titleRow(ws, 'Care Hours Report', HEADERS.length);
    subtitleRow(ws, `${from} to ${to}`, HEADERS.length);
    headerRow(ws, HEADERS);
    rows.forEach((r, i) =>
      dataRow(ws, [
        r.service_user_name, r.shift_type.replace(/_/g, ' '),
        Number(r.total_shifts), Number(r.completed_shifts), Number(r.total_hours),
      ], i + 5),
    );
    ws.getColumn(5).numFmt = '0.00';
    autoWidth(ws, HEADERS.length);
    footerRow(ws, rows.length + 6, HEADERS.length);
    return toBuffer(wb);
  }

  // ─── 6. Document expiry report ────────────────────────────────────────────

  async documentExpiryReport(
    tenantId: string,
    daysAhead = 30,
    format: 'xlsx' | 'csv' = 'xlsx',
  ): Promise<Buffer | string> {
    const rows: Array<{
      worker_name: string;
      email: string;
      doc_type: string;
      expiry_date: string;
      days_remaining: number;
      verified: boolean;
    }> = await this.dataSource.manager.query(
      `SELECT
         CONCAT(u.first_name, ' ', u.last_name) AS worker_name,
         u.email,
         d.doc_type,
         d.expiry_date::text,
         (d.expiry_date - CURRENT_DATE)         AS days_remaining,
         COALESCE(d.verified, false)            AS verified
       FROM documents d
       JOIN care_workers cw ON cw.id = d.care_worker_id AND cw.tenant_id = $1
       JOIN users u ON u.id = cw.user_id
       WHERE d.tenant_id = $1
         AND d.expiry_date IS NOT NULL
         AND d.expiry_date <= CURRENT_DATE + ($2 || ' days')::interval
         AND d.expiry_date >= CURRENT_DATE - interval '7 days'
         AND d.deleted_at IS NULL
       ORDER BY d.expiry_date`,
      [tenantId, daysAhead],
    );

    const HEADERS = [
      'Worker', 'Email', 'Document Type', 'Expiry Date', 'Days Remaining', 'Verified',
    ];

    if (format === 'csv') {
      return toCsv(HEADERS, rows.map((r) => [
        r.worker_name, r.email, r.doc_type, r.expiry_date,
        r.days_remaining, r.verified ? 'Yes' : 'No',
      ]));
    }

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Document Expiry');
    titleRow(ws, 'Document Expiry Report', HEADERS.length);
    subtitleRow(ws, `Documents expiring within ${daysAhead} days`, HEADERS.length);
    headerRow(ws, HEADERS);

    rows.forEach((r, i) => {
      const rowNum = i + 5;
      dataRow(ws, [
        r.worker_name, r.email, r.doc_type.replace(/_/g, ' '),
        r.expiry_date, Number(r.days_remaining), r.verified ? 'Yes' : 'No',
      ], rowNum);

      const daysCell = ws.getRow(rowNum).getCell(5);
      const d = Number(r.days_remaining);
      daysCell.fill = {
        type: 'pattern', pattern: 'solid',
        fgColor: { argb: d < 0 ? 'FFFEE2E2' : d <= 7 ? 'FFFEF3C7' : 'FFF0FDF4' },
      };
      daysCell.font = { bold: true, color: { argb: d < 0 ? 'FF991B1B' : d <= 7 ? 'FF92400E' : 'FF166534' } };
    });

    autoWidth(ws, HEADERS.length);
    footerRow(ws, rows.length + 6, HEADERS.length);
    return toBuffer(wb);
  }

  // ─── 7. Training compliance report ───────────────────────────────────────

  async trainingComplianceReport(
    tenantId: string,
    format: 'xlsx' | 'csv' = 'xlsx',
  ): Promise<Buffer | string> {
    const rows: Array<{
      worker_name: string;
      email: string;
      training_type: string;
      completed_at: string | null;
      expiry_date: string | null;
      status: string;
      certificate_url: string | null;
    }> = await this.dataSource.manager.query(
      `SELECT
         CONCAT(u.first_name, ' ', u.last_name) AS worker_name,
         u.email,
         t.training_type,
         t.completed_at::text,
         t.expiry_date::text,
         CASE
           WHEN t.expiry_date < CURRENT_DATE THEN 'Expired'
           WHEN t.expiry_date <= CURRENT_DATE + interval '30 days' THEN 'Expiring Soon'
           WHEN t.completed_at IS NOT NULL THEN 'Valid'
           ELSE 'Not Completed'
         END AS status,
         t.certificate_url
       FROM training t
       JOIN care_workers cw ON cw.id = t.care_worker_id AND cw.tenant_id = $1
       JOIN users u ON u.id = cw.user_id
       WHERE t.tenant_id = $1 AND t.deleted_at IS NULL
       ORDER BY worker_name, t.training_type`,
      [tenantId],
    );

    const HEADERS = [
      'Worker', 'Email', 'Training Type', 'Completed', 'Expires', 'Status', 'Certificate',
    ];

    if (format === 'csv') {
      return toCsv(HEADERS, rows.map((r) => [
        r.worker_name, r.email, r.training_type, r.completed_at ?? 'N/A',
        r.expiry_date ?? 'N/A', r.status, r.certificate_url ?? '',
      ]));
    }

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Training Compliance');
    titleRow(ws, 'Training Compliance Report', HEADERS.length);
    subtitleRow(ws, `Generated ${new Date().toLocaleDateString('en-GB')}`, HEADERS.length);
    headerRow(ws, HEADERS);

    rows.forEach((r, i) => {
      const rowNum = i + 5;
      dataRow(ws, [
        r.worker_name, r.email, r.training_type.replace(/_/g, ' '),
        r.completed_at ?? '—', r.expiry_date ?? '—', r.status,
        r.certificate_url ?? '',
      ], rowNum);

      const statusCell = ws.getRow(rowNum).getCell(6);
      const colour =
        r.status === 'Valid' ? 'FFF0FDF4' :
        r.status === 'Expiring Soon' ? 'FFFEF3C7' : 'FFFEE2E2';
      const textColour =
        r.status === 'Valid' ? 'FF166534' :
        r.status === 'Expiring Soon' ? 'FF92400E' : 'FF991B1B';
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: colour } };
      statusCell.font = { bold: true, color: { argb: textColour } };
    });

    autoWidth(ws, HEADERS.length);
    footerRow(ws, rows.length + 6, HEADERS.length);
    return toBuffer(wb);
  }
}
